/** Localized copy shared by browser and Electron Renderer hosts. */
export type AgentLocale = 'en' | 'zh-CN'

const copy = {
  en: {
    agent: 'Agent Alpha',
    newSession: 'New session',
    renameSession: 'Rename session',
    deleteSession: 'Delete session',
    settings: 'Provider settings',
    closePanel: 'Close Agent panel',
    switchLanguage: 'Switch language',
    connected: 'Connected',
    testing: 'Testing',
    notConfigured: 'Setup required',
    connectionError: 'Connection error',
    noModel: 'No model selected',
    emptyTitle: 'What should we inspect?',
    emptyBody: 'Ask about the visible chart or make a bounded chart change.',
    promptTrend: 'Summarize the current trend and key levels',
    promptRsi: 'Analyze RSI(14) over the latest 20 bars',
    promptEma: 'Add EMA(20) to the main chart',
    promptTheme: 'Switch the chart to dark theme',
    readOnly: 'Read-only',
    readOnlyHint: 'Block chart changes',
    noSymbol: 'No symbol',
    noPeriod: 'No period',
    noRange: 'No range',
    injectedKLineBars: 'Injection preview',
    injectedKLineBarsDescription: 'Preview of the ContextItem data supplied to the model.',
    showInjectedKLineBars: 'Show preview',
    hideInjectedKLineBars: 'Hide preview',
    injectedKLineBarsCount: 'ContextItems injected',
    composerPlaceholder: 'Ask about this chart...',
    send: 'Send',
    stop: 'Stop',
    steeringDisabled: 'A run is active. Your draft will stay here.',
    action: 'Action',
    reasoning: 'Reasoning',
    input: 'Input',
    result: 'Result',
    evidence: 'Evidence',
    locate: 'Locate on chart',
    undo: 'Undo',
    retry: 'Retry',
    confirm: 'Confirm',
    cancel: 'Cancel',
    reject: 'Reject',
    reversible: 'Reversible',
    irreversible: 'Not reversible',
    required: 'Confirmation required',
    recommended: 'Recommended action',
    usage: 'Usage',
    tokens: 'tokens',
    providerTitle: 'Model provider',
    tools: 'Tools',
    noTools: 'No Agent tools are registered.',
    toolParameters: 'Parameters (JSON)',
    toolRun: 'Run tool',
    toolRunning: 'Running...',
    providerBody: 'Connect your OpenAI-compatible endpoint for Agent runs.',
    providerProfile: 'Configuration',
    providerProfileName: 'Configuration name',
    newProviderProfile: 'New configuration',
    apiProtocol: 'API protocol',
    openAiCompletions: 'Open AI Completions',
    openAiResponses: 'Open AI Response',
    baseUrl: 'Base URL',
    apiKey: 'API key',
    exaApiKey: 'Exa API key',
    exaApiKeyPlaceholder: 'Leave blank to keep the saved key',
    additionalHeaders: 'Additional headers (JSON)',
    additionalHeadersPlaceholder:
      '{\n  "HTTP-Referer": "https://example.com",\n  "X-OpenRouter-Title": "My app"\n}',
    model: 'Model ID',
    testConnection: 'Test connection',
    refreshModels: 'Refresh model list',
    probeResults: 'Compatibility test results',
    probeCatalog: 'Catalog and authentication',
    probeText: 'Minimal text response',
    probeTool: 'Harmless tool call',
    apiKeyPlaceholder: 'Leave blank to use the saved credential',
    modelPlaceholder: 'Enter a model ID',
    providerDraftNotice: 'Your current draft will be preserved.',
    sessionNamePrompt: 'Session name',
    deleteSessionConfirm: 'Delete this session?',
    runStatus: 'Run status',
    status: {
      idle: 'Ready',
      running: 'Running',
      cancelling: 'Stopping',
      completed: 'Completed',
      failed: 'Failed',
      cancelled: 'Cancelled',
      partial: 'Partially completed',
      interrupted: 'Interrupted',
      queued: 'Queued',
      'requires-confirmation': 'Waiting for confirmation',
      succeeded: 'Succeeded',
      confirmed: 'Confirmed',
      rejected: 'Rejected',
      expired: 'Expired',
      undone: 'Undone',
    },
  },
  'zh-CN': {
    agent: 'Agent Alpha',
    newSession: '新建会话',
    renameSession: '重命名会话',
    deleteSession: '删除会话',
    settings: 'Provider 设置',
    closePanel: '关闭 Agent 面板',
    switchLanguage: '切换语言',
    connected: '已连接',
    testing: '测试中',
    notConfigured: '需要设置',
    connectionError: '连接错误',
    noModel: '未选择模型',
    emptyTitle: '想检查什么？',
    emptyBody: '可以询问当前可见图表，或执行边界明确的图表操作。',
    promptTrend: '总结当前趋势和关键价位',
    promptRsi: '分析最近 20 根 K 线的 RSI(14)',
    promptEma: '在主图添加 EMA(20)',
    promptTheme: '切换图表为深色主题',
    readOnly: '只读',
    readOnlyHint: '禁止修改图表',
    noSymbol: '无标的',
    noPeriod: '无周期',
    noRange: '无区间',
    injectedKLineBars: '注入预览',
    injectedKLineBarsDescription: '模型实际接收的 ContextItem 数据预览。',
    showInjectedKLineBars: '查看预览',
    hideInjectedKLineBars: '收起预览',
    injectedKLineBarsCount: '个 ContextItem 已注入',
    composerPlaceholder: '询问当前图表...',
    send: '发送',
    stop: '停止',
    steeringDisabled: '任务正在运行，当前草稿会保留。',
    action: '操作',
    reasoning: '思考过程',
    input: '输入',
    result: '结果',
    evidence: '证据',
    locate: '在图表中定位',
    undo: '撤销',
    retry: '重试',
    confirm: '确认',
    cancel: '取消',
    reject: '拒绝',
    reversible: '可撤销',
    irreversible: '不可撤销',
    required: '需要确认',
    recommended: '建议操作',
    usage: '用量',
    tokens: 'tokens',
    providerTitle: '模型 Provider',
    tools: '工具',
    noTools: '当前没有已注册的 Agent 工具。',
    toolParameters: '参数（JSON）',
    toolRun: '运行工具',
    toolRunning: '运行中...',
    providerBody: '连接你自己的 OpenAI-compatible 端点以运行 Agent。',
    providerProfile: '配置',
    providerProfileName: '配置名称',
    newProviderProfile: '新建配置',
    apiProtocol: 'API 协议',
    openAiCompletions: 'Open AI Completions',
    openAiResponses: 'Open AI Response',
    baseUrl: 'Base URL',
    apiKey: 'API key',
    exaApiKey: 'Exa API key',
    exaApiKeyPlaceholder: '留空则保留已保存的 Key',
    additionalHeaders: '附加请求头（JSON）',
    additionalHeadersPlaceholder:
      '{\n  "HTTP-Referer": "https://example.com",\n  "X-OpenRouter-Title": "我的应用"\n}',
    model: '模型 ID',
    testConnection: '测试连接',
    refreshModels: '刷新模型列表',
    probeResults: '兼容性测试结果',
    probeCatalog: '模型目录与鉴权',
    probeText: '最小文本回复',
    probeTool: '无副作用工具调用',
    apiKeyPlaceholder: '留空则使用已保存的凭据',
    modelPlaceholder: '输入模型 ID',
    providerDraftNotice: '当前草稿会保留。',
    sessionNamePrompt: '会话名称',
    deleteSessionConfirm: '删除这个会话？',
    runStatus: '运行状态',
    status: {
      idle: '就绪',
      running: '运行中',
      cancelling: '正在停止',
      completed: '已完成',
      failed: '失败',
      cancelled: '已取消',
      partial: '部分完成',
      interrupted: '已中断',
      queued: '排队中',
      'requires-confirmation': '等待确认',
      succeeded: '成功',
      confirmed: '已确认',
      rejected: '已拒绝',
      expired: '已过期',
      undone: '已撤销',
    },
  },
} as const

export function getAgentCopy(locale: AgentLocale) {
  return copy[locale]
}
